export const words = {
  Nav: ["home", "programs", "why us", "plans", "testimonilas"],
  best_fitness: "the best fitness club in the town",
  SHAPE: "SHAPE",
  IDEAL_body: "IDEAL BODY",
  shape_dec:
    "In here we will help you to shape and build your ideal body and live up your life to fullest",
  startedbtn: "Get Started",
  learnmore: "Learn More",
  btn_join: "Join Now",
  heart_rate: "Heart Rate",
  haert_num: "116 bpm",
  Calories: "Calories burned",
  kcal: "220 kcal",
  EXPLORE_OUR: "EXPLORE OUR",
  PROGRAMS: "PROGRAMS",
  TO_SHAPE_YOU: "TO SHAPE YOU",
  SOME_REASONS: "SOME REASONS",
  CHOOSE_Us: " CHOOSE US?",
  WHY: "WHY",
  READY_TO_START: "READY TO START",
  YOUR_JOURNEY: "YOUR JOURNEY",
  NOW_WITHUS: "NOW WITHUS",
};
